class Config():
    img_dir = ''
    gt_dir = ''
    test_img_dir2 = ''
    test_gt_dir2 = ''
    test_img_dir1 = ''
    test_gt_dir1 = ''
    GPU = 2
    base_number = 40
    scal_h = 3
    scal_w = 1935 / 640
    resize_h = 800
    resize_w = 640
    sigma = 10
    point_num = 19
    num_epochs = 300
    lr = 1e-4
    save_model_path = ''
    save_results_path = ''
